# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 918dd819e9c295edfda667d127a929995e2e4c8b8c7f7dd93c166caab92de248f5dd7b9b4f98bd80d117fc2ab64cd99ecb6c80f8549ef3c48756072d6028c4b4

test:
  secret_key_base: f5e54d08a97002d6b648c26e49bd9d8bb51f46f77139fcd9bb07f2bc51f70a4c6e4587c46697c9ecdf751892b597566a6a847e46054659b6a11fceb6c234459d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
